### ISSUE TITLE
General Question regarding reset running statistics of BN

### ISSUE THREAD

**Issue by TianpengBu** [xfey/pytorch-BigNAS#3]
Hi thanks for your great work! I got a question regarding your implementation of `def reset_running_stats_for_calibration`. I find that you set bn.momentum=None, which means that you calibtrate BN layers by using exponential moving average. Why you do this in this way rather than set bn.momentum unchanged? 

I'm looking forward to hearing your feedback.
Best regards,

**Comment by xfey** [comment]
Hi👋, thanks for using our code!

Using EMA or not does make some difference, so I took a look at the source code. The implementation here follows the source code from [function in AttentiveNAS](https://github.com/facebookresearch/AttentiveNAS/blob/c4c16f174dd1acfdeecd93cef1acd5afd92eb317/models/attentive_nas_static_model.py#L91), and I have checked the similar approach using in the Once-for-All (OFA) network. The same code is found in [code from OFA](https://github.com/mit-han-lab/once-for-all/blob/a5381c1924d93e582e4a321b3432579507bf3d22/ofa/imagenet_classification/elastic_nn/modules/dynamic_op.py#L254) and [code from AttentiveNAS](https://github.com/facebookresearch/AttentiveNAS/blob/c4c16f174dd1acfdeecd93cef1acd5afd92eb317/models/modules/dynamic_ops.py#L224). Both of them are migrated from the official implementation of PyTorch, but AttentiveNAS comments it out and does not implement such process, which leads to the unimplemented EMA. 

However, [this line](https://github.com/facebookresearch/AttentiveNAS/blob/c4c16f174dd1acfdeecd93cef1acd5afd92eb317/models/modules/dynamic_ops.py#L160) of the DynamicBN function in AttentiveNAS also leaves a comment and some related links. But I couldn't find a specific reason for not using momentum in the linked paper and webpage. You can check out these links and we would be grateful to be able to get your feedback.

Best regards.
